### ISSUE TITLE
Prisijungimo duomenys kode

### ISSUE THREAD

**Issue by JanisVepris** [vilnius/taryba-software#1]
Sveiki, kažkas kode paliko FTP prisijungimo duomenis.

<img width="780" alt="screen shot 2018-02-12 at 22 31 35" src="https://user-images.githubusercontent.com/4033838/36118613-529d67c2-1046-11e8-9a25-53305251fe8b.png">

**Comment by jonaspidkovas** [comment]
duomenys pašalinti

**Comment by eimantas** [comment]
@emiestas Nors slaptažodžiai pašalinti iš kodo - jie liko kodo istorijoje (kas bus matoma ypač po commit'o žinutės). Būtų gerai perrašyti visą git'o istoriją arba pašalinti ją visai ir iš naujo inicializuoti. Tada niekas net žiūrėdamas komitų istoriją nematytų įvestų slaptažodžių.

**Comment by jonaspidkovas** [comment]
Slaptažodis buvo pakeistas
